name: ngombi_app
description: "Application NGOMBI - TV & Radio en direct"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.0

  # Versions compatibles Dart 3.0.4
  webview_flutter: ^4.7.0
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Requis pour l'étape Generate App Icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuration des icônes d'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
